import { defineEventHandler, setHeader } from 'h3'
/* @ts-expect-error virtual module generated by the nuxt-actions module when openapi is enabled */
import { swaggerHtml } from '#actions-openapi-registry'

export default defineEventHandler((event) => {
  setHeader(event, 'content-type', 'text/html')
  return swaggerHtml
})
