import { defineEventHandler } from 'h3'
/* @ts-expect-error virtual module generated by the nuxt-actions module when openapi is enabled */
import { actions, info } from '#actions-openapi-registry'
import { collectSchemas, buildOpenApiDocument } from './utils/openapi'

/*
 * The action registry is fixed at build time, so the document is invariant —
 * build it once and reuse it instead of re-running schema conversion on every
 * request.
 */
let cachedDocument: Promise<unknown> | undefined

export default defineEventHandler(() => {
  cachedDocument ??= (async () => {
    const schemas = await collectSchemas(actions)
    return buildOpenApiDocument({ actions, schemas, info })
  })()
  return cachedDocument
})
