import { defineEventHandler } from 'h3'
/* @ts-expect-error virtual module generated by the nuxt-actions module when openapi is enabled */
import { actions, info } from '#actions-openapi-registry'
import { collectSchemas, buildOpenApiDocument } from './utils/openapi'

export default defineEventHandler(async () => {
  const schemas = await collectSchemas(actions)
  return buildOpenApiDocument({ actions, schemas, info })
})
